name: Test Project
on: push
jobs: 
  test:
    runs-out: ubuntu-latest
    stpes:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18